# Generated by Django 4.1.2 on 2022-11-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_author',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/%y/%m/%d'),
        ),
    ]
